# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      username:
        description: 'Author Twitter'
        default: 'tiulpin'
        required: true
      id:
        description: 'First Tweet ID'
        default: '1282761905426358272'
        required: true
      date:
        description: 'Date'
        default: '13 July 2020'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v4.0.0
      with:
        node-version: 10.16.0

    - name: Prepare things
      run: |
        git config --local user.email "viktor@tiulp.in"
        git config --local user.name "tiulpin"
        npm install

    - name: Add the author
      env:
        NAME: ${{ github.event.inputs.username }}
        DATE: ${{ github.event.inputs.date }}
        TWEET_ID: ${{ github.event.inputs.id }}
      run: |
        sed -ie "4s/$/ \n  { username: '$NAME', start: '$DATE', first: '$TWEET_ID', post: true, update: true},/" authors.js
 
    - name: Get dump
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        npm run update
        git add dump/*
        git commit -m "🎉 New week, new author" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
        
    - name: Publish
      env:
        NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        AUTHOR: ${{ github.event.inputs.username }}
        AUTHOR_IMAGE: "https://github.com/tiulpin/ds.underhood.club/blob/master/dump/images/${{ github.event.inputs.username }}-image.jpg?raw=true"
        UNDERHOOD: "dsunderhood"
        CF_ID: "7f1ab247128519dca5e3b36c3baa218a"
        ARCHIVE_SLUG: "40040c5fb4f04fb2af8c61d9557547a3"   
      run: |
        pip install notion==0.0.25 requests==2.24.0
        python build_website.py
